#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

if [ ! -d libs/IInAppBillingService.jar ];
then
    curl -L -o libs/IInAppBillingService.jar http://library.soom.la/fetch/android-store-google-play-iab/3?cf=dl_deps
fi